### ISSUE TITLE
Add support for reading user input in the middle of script execution.

### ISSUE THREAD

**Issue by rasoulMrz** [Utopia42-club/utopia42-web#10]
an example pseudo code that should be supported in plugins:

```
for i in range(10):
     type = getInputFromUser({label: 'choose your i'th block type', type:'blockType' });
```

**Comment by Navid-Fkh** [comment]
UtopiaApi.getInputsFromUser(inputs) method added.
inputs is the list of plugin parameters (same format as plugin descriptor)
