### ISSUE TITLE
Add support fo reviewing plugin source code, before execution

### ISSUE THREAD

**Issue by rasoulMrz** [Utopia42-club/utopia42-web#7]
As we are using `eval` to run a code from a given link. it is better if users can review the source code before execution, so they can prevent executing unwanted scripts.

**Comment by Navid-Fkh** [comment]
I think the majority of users wont have the knowledge to review the code and those
curious one can open links and check the source code themselves ( maybe adding a clickable link somewhere? )

**Comment by rasoulMrz** [comment]
This is like the "I accept the rules" check box in every signup dialog, which most of the people just check it.
The point is by doing this users know that they are responsible for any threat or malware!
Like bitcoin mining scripts :)

to prevent any bug or hack we should show the exact code that we are about to run! not a URL.

**Comment by rasoulMrz** [comment]
Note that a primary version that shows a code as text does not cost too much to implement

**Comment by aminabs** [comment]
check this out https://codemirror.net/

use the js viewer if it is small in size

**Comment by Navid-Fkh** [comment]
A simple version is now implemented.
